version: "3"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  app:
    build: .
    labels:
      - traefik.backend=automotron
      - traefik.frontend.rule=Host:automotron.lipsumar.io
      - traefik.docker.network=proxy
      - traefik.port=3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/prod
      - PUBLIC_DIR=dist
    networks: 
      - proxy
      - internal
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks: 
      - internal
    labels:
      - traefik.enable=false

