version: "3"

services:
  app:
    build: .
    labels:
      - "traefik.http.routers.automotron.rule=Host(`automotron.lipsumar.io`)"
      - "traefik.http.routers.automotron.tls.certresolver=le"
      - "traefik.http.routers.automotron.entrypoints=websecure"
      - "traefik.docker.network=traefik-external"
    environment:
      - MONGO_URL=mongodb://mongo:27017/prod
      - PUBLIC_DIR=dist
      - API_BASE_URL=http://automotron.lipsumar.io
    networks: 
      - traefik-external
      - internal
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks: 
      - internal
    labels:
      - "traefik.enable=false"

networks:
  traefik-external:
    external: true
  internal:
    external: false