name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: appleboy/ssh-action@master
      name: Deploy via SSH
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: 22
        timeout: 2m
        command_timeout: 2m
        script: |
          cd automotron
          git pull
          docker-compose up --build -d

